version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: autocannon
    versions:
    - 7.0.3
    - 7.0.4
    - 7.0.5
    - 7.1.0
  - dependency-name: "@sinonjs/fake-timers"
    versions:
    - 7.0.2
    - 7.0.4
  - dependency-name: fastify-websocket
    versions:
    - 3.0.0
    - 3.0.1
    - 3.1.0
  - dependency-name: fastify-static
    versions:
    - 4.0.0
  - dependency-name: graphql-tools
    versions:
    - 7.0.2
    - 7.0.3
